=head1 NAME

Kwiki::Raw - Provide an action to retrieve the raw wikitext of a page

=head1 DESCRIPTION

Sometimes it is handy to view the wiki source of a page, without
going through the hassle of loading the edit pane. This lets you
do that. Any page content is viewable. If the page does not exist,
an empty response is provided (this may change in the future).

Note: it appears that this plugin may override the controls that
Kwiki::PagePrivacy provides, so if you are using that plugin, don't
use this one. 

=head1 AUTHORS

Chris Dent, <cdent@burningchrome.com>

=head1 SEE ALSO

L<Kwiki>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2005, Chris Dent

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.
