## Support for Perldoc POD Generation
#
# This module adds a `perldoc` target to the `Makefile` for authors.
# This means that `make perldoc` will create `.pod` files from every
# `.pm` file with *Perldoc* style documentation.
#
# Synopsis:
# 
#     > make perldoc
#
# Copyright (c) 2007. Ingy döt Net. All rights reserved.
#
# Licensed under the same terms as Perl itself.

package Module::Install::Perldoc;

use strict;
use Module::Install::Base;
use File::Basename ();

use vars qw{$VERSION @ISA};
BEGIN {
    $VERSION = '0.10';
    @ISA     = qw{Module::Install::Base};
}

## Support for author side Perldoc management
sub perldoc {
    my $self = shift;
    require File::Find;

    # Need to find all the .pm files at `perl Makefile.PL` time
    my @pms = glob('*.pm');
    File::Find::find( sub {
        push @pms, $File::Find::name if /\.pm$/i;
    }, 'lib');

    my $postamble = <<'.';
doc :: perldoc
pod :: perldoc
perldoc ::
.

    # Add actions for `make perldoc`
    for my $pm (@pms) {
        $postamble .= <<".";
\t\@\$(PERL) -Ilib -MPerldoc::Make=pm_into_pod - $pm
.
    }

    $self->postamble($postamble)
        if @pms;
}

1;
=for perldoc
This POD generated by Perldoc-0.21.
DO NOT EDIT. Your changes will be lost.

=head1 NAME

Module::Install::Perldoc - Support for Perldoc POD Generation

=head1 DESCRIPTION

This module adds a C<perldoc> target to the C<Makefile> for authors.
This means that C<make perldoc> will create C<.pod> files from every
C<.pm> file with B<Perldoc> style documentation.

Synopsis:

    > make perldoc

=head1 AUTHOR

Ingy döt Net

=head1 COPYRIGHT

Copyright (c) 2007. Ingy döt Net. All rights reserved.

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.

See http://www.perl.com/perl/misc/Artistic.html

=cut
