links: core plugins

#-------------------------------------------------------------------------------
include ../../src/core/docs.mk
include ../../src/plugins/docs.mk

#-------------------------------------------------------------------------------
$(CORE_PATHS) $(CPAN_PATHS) $(PLUGINS_PATHS):
		mkdir -p $@
