=head1 NAME

Kwiki::PageTemperature - Provide a visual cue to the age of a page

=head1 DESCRIPTION

Add a status that provides a colored cue to the age of a page. The
color is a combination of red and blue. The more recently changed
the page, the more red.

As distributed a page that is 60 or more days "cold" will show an
all blue status. In the future this time span will be chosen from
a preference.

=head1 AUTHORS

Chris Dent, <cdent@burningchrome.com>

=head1 SEE ALSO

L<Kwiki>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2005, Chris Dent

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.
