=head1 NAME

Kwiki::Formatter::CaptionedImage - Will display an image to the screen with a
caption below it.

=head1 VERSION

Version 0.01

=head1 SYNOPSIS

This module handles the common idiom of displaying a caption below an image
This is very common in manuals and more formal documents. Syntax is basically
the same as a titled external link but the URL points to an image instead of
a document.

In your wiki markup:

    [http://foo.com/images/foo.gif Picture of Footastic product]

The HTML produced should be something like:

    <table class="captioned_image">
        <tbody><tr><td><img src="http://foo.com/images/foo.gif" /></td></tr></tbody>
        <tfoot><tr><th>Picture of Footastic product</th></tr></tfoot>
    </table>

With the default stylesheets this will look something like:

    |------------------------------|
    |                              |
    |     <Pic displays here>      |
    |                              |
    |------------------------------|
    | Picture of Footastic product |
    |------------------------------|

=head1 Floating the image

By default the captioned image is centered on the screen with both sides
cleared. You can also float the captioned image left or right and the text
will flow around it.

For a left floated image:

    [left| http://foo.com/images/foo.gif Picture of Footastic product]

For a right floated image:

    [right| http://foo.com/images/foo.gif Picture of Footastic product]

=head1 AUTHOR

Eric Anderson, C<< <eric at cordata.com> >>

=head1 COPYRIGHT & LICENSE

Copyright 2006 CorData, all rights reserved.

This program is free software; you can redistribute it and/or modify it under
the same terms as Perl itself. See http://www.perl.com/perl/misc/Artistic.html
