## Documentation Framework for Perl
#
# Perldoc is meant to be a full featured documentation framework for Perl.
#
# Copyright (c) 2007. Ingy döt Net. All rights reserved.
#
# Licensed under the same terms as Perl itself.

package Perldoc;
use 5.006001;
use strict;
use warnings;
our $VERSION = '0.21';

1;
=for perldoc
This POD generated by Perldoc-0.21.
DO NOT EDIT. Your changes will be lost.

=head1 NAME

Perldoc - Documentation Framework for Perl

=head1 DESCRIPTION

Perldoc is meant to be a full featured documentation framework for Perl.

=head1 AUTHOR

Ingy döt Net

=head1 COPYRIGHT

Copyright (c) 2007. Ingy döt Net. All rights reserved.

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.

See http://www.perl.com/perl/misc/Artistic.html

=cut
