#!/usr/bin/env perl
use 5.008003;
use strict;
use warnings;
our $VERSION = '0.40';
use Cwd 'cwd', 'abs_path';
use FindBin;
use Config;

sub find_base {
    return if defined $ENV{KWIKI_BASE};

    my $base = $FindBin::Bin;
    my $bin = $0;
    $bin =~ s/.*\///;
    $bin = "$base/$bin";
    my $home = cwd();
    while (-l $bin) {
        chdir $base;
        $bin = abs_path(readlink $bin);
        $base = $bin;
        $base =~ s/(.*)\/.*/$1/;
    }
    chdir $home;
    $base = abs_path("$base/../../..");

    die "*ERROR*: Can't locate Kwiki base repository."
        unless -d "$base/lib/Kwiki" and -d "$base/src/core/Kwiki";
    $ENV{KWIKI_BASE} = $base;
} 

# Add $KWIKI_BASE/lib to @INC;
BEGIN {
    # $ENV{KWIKI_TEST} = 1;
    if ($ENV{KWIKI_TEST}) {
        @INC = (
            $Config::Config{archlib},
            $Config::Config{privlib},
        ); 
    }

    find_base();
    eval "use lib '$ENV{KWIKI_BASE}/lib'; 1" or die $@;
}

use Kwiki::Boot;
Kwiki::Boot->class->new->kwiki->hub->command->process(@ARGV)->hub->remove_hooks;

__END__

=head1 NAME

kwiki - The Kwiki Command Line Tool

=head1 USAGE

    > kwiki -new /path/to/cgi-bin/my-kwiki

    Kwiki software installed! Point your browser at this location.

=head1 DESCRIPTION

Kwiki is a simple extendable wiki framework, written in Perl.

See L<Kwiki::Command> for more information on using this command line tool.

=head1 NOTE

If you are on Mac OS X, use the command C<perldoc Kwiki.pm> to get the
Kwiki B<module> documentation.

=head1 AUTHOR

Ingy döt Net <ingy@cpan.org>

=head1 COPYRIGHT

Copyright (c) 2004-2005. Brian Ingerson. All rights reserved.

Copyright (c) 2006. Ingy döt Net. All rights reserved.

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.

See http://www.perl.com/perl/misc/Artistic.html

=cut

# vim: set ft=perl:
