PLUGIN_PATHS = \
	Kwiki/Ajax \
	Kwiki/Atom \
	Kwiki/Command \
	Kwiki/DB \
	Kwiki/Edit \
	Kwiki/Formatter \
	Kwiki/Icons \
	Kwiki/Notify \
	Kwiki/Pages \
	Kwiki/Purple \
	Kwiki/SOAP \
	Kwiki/Search \
	Kwiki/UniUI \
	Kwiki/UserMessage \
	Kwiki/UserName \
	Kwiki/Users \
	Kwiki/Widgets \
	Kwiki/Template/TT2 \
	Kwiki/Template/TT2/UTF8 \

PLUGIN_LEVEL_2 = \
	Kwiki/AdSense.pm \
	Kwiki/Ajax.pm \
	Kwiki/AnchorLink.pm \
	Kwiki/Atom.pm \
	Kwiki/Attachments.pm \
	Kwiki/AuthorOnlyPageEditing.pm \
	Kwiki/Autoformat.pm \
	Kwiki/Backlinks.pm \
	Kwiki/Blog.pm \
	Kwiki/BreadCrumbs.pm \
	Kwiki/Cache.pm \
	Kwiki/CachedDisplay.pm \
	Kwiki/Comments.pm \
	Kwiki/ConfigBlocks.pm \
	Kwiki/CoolURI.pm \
	Kwiki/DB.pm \
	Kwiki/DNSBL.pm \
	Kwiki/DatedAnnounce.pm \
	Kwiki/DeletePage.pm \
	Kwiki/Diff.pm \
	Kwiki/Docsite.pm \
	Kwiki/Doolittle.pm \
	Kwiki/DoubleClickToEdit.pm \
	Kwiki/Emoticon.pm \
	Kwiki/Favorites.pm \
	Kwiki/FetchRSS.pm \
	Kwiki/ForeignLinkGlyphs.pm \
	Kwiki/GDGraphGenerator.pm \
	Kwiki/GuestBook.pm \
	Kwiki/HanConvert.pm \
	Kwiki/HomePagePreference.pm \
	Kwiki/HtmlBlocks.pm \
	Kwiki/IRCMode.pm \
	Kwiki/Infobox.pm \
	Kwiki/Invite.pm \
	Kwiki/Keywords.pm \
	Kwiki/LiveSearch.pm \
	Kwiki/Markdown.pm \
	Kwiki/MindMap.pm \
	Kwiki/ModPerl.pm \
	Kwiki/NavigationToolbar.pm \
	Kwiki/NewPage.pm \
	Kwiki/Oreo.pm \
	Kwiki/Orphans.pm \
	Kwiki/Outline2HTML.pm \
	Kwiki/PPerl.pm \
	Kwiki/PageInclude.pm \
	Kwiki/PagePrivacy.pm \
	Kwiki/PageStats.pm \
	Kwiki/PageTemperature.pm \
	Kwiki/PageTemplate.pm \
	Kwiki/ParagraphBlocks.pm \
	Kwiki/PerlTidyBlocks.pm \
	Kwiki/PerlTidyModule.pm \
	Kwiki/PodBlocks.pm \
	Kwiki/PoweredBy.pm \
	Kwiki/PreformattedBlocks.pm \
	Kwiki/Purple.pm \
	Kwiki/Raw.pm \
	Kwiki/RecentChanges.pm \
	Kwiki/Revisions.pm \
	Kwiki/SOAP.pm \
	Kwiki/Scode.pm \
	Kwiki/Search.pm \
	Kwiki/Session.pm \
	Kwiki/ShellBlocks.pm \
	Kwiki/SocialMap.pm \
	Kwiki/Spaces.pm \
	Kwiki/Spork.pm \
	Kwiki/Technorati.pm \
	Kwiki/Test.pm \
	Kwiki/Textile.pm \
	Kwiki/TimeZone.pm \
	Kwiki/Trackback.pm \
	Kwiki/Transclude.pm \
	Kwiki/URLBlock.pm \
	Kwiki/UniUI.pm \
	Kwiki/UserMessage.pm \
	Kwiki/UserName.pm \
	Kwiki/UserPhoto.pm \
	Kwiki/UserPreferences.pm \
	Kwiki/VimMode.pm \
	Kwiki/Weather.pm \
	Kwiki/WeblogUpdates.pm \
	Kwiki/Wikiwyg.pm \
	Kwiki/Yahoo.pm \
	Kwiki/Zipcode.pm \

PLUGIN_LEVEL_3 = \
	Kwiki/Ajax/Toolman.pm \
	Kwiki/Archive/Rcs.pm \
	Kwiki/Archive/SVK.pm \
	Kwiki/Atom/Server.pm \
	Kwiki/Command/Edit.pm \
	Kwiki/Command/RecentChanges.pm \
	Kwiki/DB/ClassDBI.pm \
	Kwiki/DB/DBI.pm \
	Kwiki/Edit/Scode.pm \
	Kwiki/Edit/SubEtha.pm \
	Kwiki/Formatter/Pod.pm \
	Kwiki/Icons/Gnome.pm \
	Kwiki/Notify/IRC.pm \
	Kwiki/Pages/Perldoc.pm \
	Kwiki/Purple/Sequence.pm \
	Kwiki/SOAP/Fortune.pm \
	Kwiki/SOAP/Google.pm \
	Kwiki/Search/Plucene.pm \
	Kwiki/Theme/Ajax.pm \
	Kwiki/Theme/Bluepole.pm \
	Kwiki/Theme/CPB.pm \
	Kwiki/Theme/ColumnLayout.pm \
	Kwiki/Theme/HLB.pm \
	Kwiki/Theme/Klassik.pm \
	Kwiki/Theme/Selectable.pm \
	Kwiki/Theme/YAPCChicago.pm \
	Kwiki/UniUI/Theme.pm \
	Kwiki/UserMessage/CDBI.pm \
	Kwiki/UserName/Auth.pm \
	Kwiki/UserName/Remote.pm \
	Kwiki/Users/Auth.pm \
	Kwiki/Users/Remote.pm \
	Kwiki/Widgets/Links.pm \

PLUGIN_LEVEL_4 = \
	Kwiki/Template/TT2/UTF8.pm \

PLUGIN_LEVEL_5 = \
	Kwiki/Template/TT2/UTF8/Provider.pm \

PLUGIN_MODULES = $(PLUGIN_LEVEL_2) $(PLUGIN_LEVEL_3) \
		 $(PLUGIN_LEVEL_4) $(PLUGIN_LEVEL_5) \

