# We need to decide what we will support with these make files
#
# Which make will we support?
# * gmake
# * pmake ? 
#
# How do I pass the current make environment to another sub-make?

FOO:=$(shell ls)
BAR:=$(shell exit)

all:
	# make sure libs tree is up to date
