links: core cpan plugins socialtext

#-------------------------------------------------------------------------------
include ../src/core/modules.mk
include ../src/cpan/modules.mk
include ../src/plugins/modules.mk
include ../src/socialtext/modules.mk

#-------------------------------------------------------------------------------
$(CORE_PATHS) $(CPAN_PATHS) $(PLUGINS_PATHS) $(SOCIALTEXT_PATHS):
		mkdir -p $@
