=head1 NAME

Kwiki::Theme::Hatena - Kwiki Hatena Theme

=head1 SYNOPSIS

In C<config.yaml>:

    hatena_theme_logo_width: 60
    hatena_theme_logo_height: 60

=head1 DESCRIPTION

=head1 AUTHOR

Kazuhiro Osawa E<lt>ko@yappo.ne.jpE<gt>

=head1 LICENSE

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

But C<theme/hatena/template/tt2/kwiki_screen.html> and C<theme/hatena/css/kwiki.css> is the GPL License. 

=head1 SEE ALSO

L<http://d.hatena.ne.jp>
