## Base Class for Perldoc Classes
#
# Perldoc is Spiffy.
#
# Copyright (c) 2007. Ingy döt Net. All rights reserved.
#
# Licensed under the same terms as Perl itself.

package Perldoc::Base;
use strict;
use warnings;
use IO::All -utf8;
use Class::Field 0.10 qw'field const';
use XXX;

## Synopsis:
# 
#     package Perldoc::Foo;
#     use Perldoc::Base -Base;

sub import {
    my $class = shift;
    my $flag = $_[0] || '';
    my $package = caller;
    if ($flag eq '-base') {
        no strict 'refs';
        push @{$package . "::ISA"}, $class;
        *{$package . "::$_"} = \&$_
          for qw'io field const WWW XXX YYY ZZZ';
    }
}

sub new {
    my $class = shift;
    return bless {@_}, $class;
}

1;
=for perldoc
This POD generated by Perldoc-0.21.
DO NOT EDIT. Your changes will be lost.

=head1 NAME

Perldoc::Base - Base Class for Perldoc Classes

=head1 SYNOPSIS

    package Perldoc::Foo;
    use Perldoc::Base -Base;

=head1 DESCRIPTION

Perldoc is Spiffy.

=head1 AUTHOR

Ingy döt Net

=head1 COPYRIGHT

Copyright (c) 2007. Ingy döt Net. All rights reserved.

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.

See http://www.perl.com/perl/misc/Artistic.html

=cut
